In [1]:
import pandas as pd
import numpy as np
from sklearn import metrics

In [2]:
training = pd.read_csv('C:/Users/Shail/Desktop/Datasets/titanic_data.csv', sep=',')
training.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [3]:
training['Cabin'].fillna(0).value_counts()

0              687
B96 B98          4
G6               4
C23 C25 C27      4
F33              3
F2               3
D                3
E101             3
C22 C26          3
C2               2
B22              2
C83              2
B20              2
D17              2
F G73            2
E24              2
C125             2
B35              2
C68              2
C52              2
D35              2
E44              2
B28              2
D36              2
E121             2
E8               2
C78              2
D33              2
D20              2
E25              2
              ... 
D11              1
B38              1
D21              1
T                1
D37              1
C46              1
E31              1
B50              1
B69              1
A23              1
E10              1
C148             1
C49              1
A19              1
E12              1
D48              1
C50              1
C85              1
B94              1
D50              1
D6               1
A20         

In [4]:
training = training.drop(['Name', 'Ticket', 'Cabin'], axis=1)
training.head(10)

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    male  22.0      1      0   7.2500        S
1            2         1       1  female  38.0      1      0  71.2833        C
2            3         1       3  female  26.0      0      0   7.9250        S
3            4         1       1  female  35.0      1      0  53.1000        S
4            5         0       3    male  35.0      0      0   8.0500        S
5            6         0       3    male   NaN      0      0   8.4583        Q
6            7         0       1    male  54.0      0      0  51.8625        S
7            8         0       3    male   2.0      3      1  21.0750        S
8            9         1       3  female  27.0      0      2  11.1333        S
9           10         1       2  female  14.0      1      0  30.0708        C

In [5]:
training.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Fare           891 non-null float64
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(2)
memory usage: 62.7+ KB


In [6]:
training['Embarked'].value_counts().plot(kind='bar')

In [7]:
training['Embarked'] = training['Embarked'].fillna('S')
training = training.fillna(0)
training.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Sex            891 non-null object
Age            891 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Fare           891 non-null float64
Embarked       891 non-null object
dtypes: float64(2), int64(5), object(2)
memory usage: 62.7+ KB


In [8]:
embarked_dummies = pd.get_dummies(training['Embarked'])
embarked_dummies.head(10)

C  Q  S
0  0  0  1
1  1  0  0
2  0  0  1
3  0  0  1
4  0  0  1
5  0  1  0
6  0  0  1
7  0  0  1
8  0  0  1
9  1  0  0

In [9]:
training = training.join(embarked_dummies)
training.head(10)

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0            1         0       3    male  22.0      1      0   7.2500   
1            2         1       1  female  38.0      1      0  71.2833   
2            3         1       3  female  26.0      0      0   7.9250   
3            4         1       1  female  35.0      1      0  53.1000   
4            5         0       3    male  35.0      0      0   8.0500   
5            6         0       3    male   0.0      0      0   8.4583   
6            7         0       1    male  54.0      0      0  51.8625   
7            8         0       3    male   2.0      3      1  21.0750   
8            9         1       3  female  27.0      0      2  11.1333   
9           10         1       2  female  14.0      1      0  30.0708   

  Embarked  C  Q  S  
0        S  0  0  1  
1        C  1  0  0  
2        S  0  0  1  
3        S  0  0  1  
4        S  0  0  1  
5        Q  0  1  0  
6        S  0  0  1  
7        S  0  0  1  
8        S  0  0  1  
9        C  1  0  0

In [10]:
sex_dummies = pd.get_dummies(training['Sex'])
training = training.join(sex_dummies)
training = training.drop(['Embarked', 'Sex'], axis=1)
training.head(10)

PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare  C  Q  S  \
0            1         0       3  22.0      1      0   7.2500  0  0  1   
1            2         1       1  38.0      1      0  71.2833  1  0  0   
2            3         1       3  26.0      0      0   7.9250  0  0  1   
3            4         1       1  35.0      1      0  53.1000  0  0  1   
4            5         0       3  35.0      0      0   8.0500  0  0  1   
5            6         0       3   0.0      0      0   8.4583  0  1  0   
6            7         0       1  54.0      0      0  51.8625  0  0  1   
7            8         0       3   2.0      3      1  21.0750  0  0  1   
8            9         1       3  27.0      0      2  11.1333  0  0  1   
9           10         1       2  14.0      1      0  30.0708  1  0  0   

   female  male  
0       0     1  
1       1     0  
2       1     0  
3       1     0  
4       0     1  
5       0     1  
6       0     1  
7       0     1  
8       1     0  
9       1     0

In [11]:
training = training.drop(['S', 'male'], axis=1)
training.head(10)

PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare  C  Q  female
0            1         0       3  22.0      1      0   7.2500  0  0       0
1            2         1       1  38.0      1      0  71.2833  1  0       1
2            3         1       3  26.0      0      0   7.9250  0  0       1
3            4         1       1  35.0      1      0  53.1000  0  0       1
4            5         0       3  35.0      0      0   8.0500  0  0       0
5            6         0       3   0.0      0      0   8.4583  0  1       0
6            7         0       1  54.0      0      0  51.8625  0  0       0
7            8         0       3   2.0      3      1  21.0750  0  0       0
8            9         1       3  27.0      0      2  11.1333  0  0       1
9           10         1       2  14.0      1      0  30.0708  1  0       1

In [12]:
training.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  891.000000  891.000000   
mean    446.000000    0.383838    2.308642   23.799293    0.523008   
std     257.353842    0.486592    0.836071   17.596074    1.102743   
min       1.000000    0.000000    1.000000    0.000000    0.000000   
25%     223.500000    0.000000    2.000000    6.000000    0.000000   
50%     446.000000    0.000000    3.000000   24.000000    0.000000   
75%     668.500000    1.000000    3.000000   35.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare           C           Q      female  
count  891.000000  891.000000  891.000000  891.000000  891.000000  
mean     0.381594   32.204208    0.188552    0.086420    0.352413  
std      0.806057   49.693429    0.391372    0.281141    0.477990  
min      0.000000    0.000000    0.000000    0.000000    0.000000  
25%      0.000000    7.910400    0.000000    0.000000    0.000000  
50%      0.000000   14.454200    0.000000    0.000000    0.000000  
75%      0.000000   31.000000    0.000000    0.000000    1.000000  
max      6.000000  512.329200    1.000000    1.000000    1.000000

In [13]:
training['Survived'].mean()

0.3838383838383838

In [14]:
training['Survived'].groupby(training['female']).mean()

female
0    0.188908
1    0.742038
Name: Survived, dtype: float64

In [15]:
training_data = training.values[:,2:]
training_target = training.values[:,1]
training_target[:5]

array([ 0.,  1.,  1.,  1.,  0.])

In [16]:
test = pd.read_csv('C:/Users/Shail/Desktop/Datasets/test.csv', sep=',')
test = test.drop(['Name', 'Ticket', 'Cabin'], axis=1)
test['Embarked'] = test['Embarked'].fillna(method='ffill')
test = test.fillna(0)
embarked_dummies = pd.get_dummies(test['Embarked'])
test = test.join(embarked_dummies)
sex_dummies = pd.get_dummies(test['Sex'])
test = test.join(sex_dummies)
test = test.drop(['Embarked', 'Sex'], axis=1)
test = test.drop(['S', 'male'], axis=1)
test_data = test.values
test_data[:3]

array([[ 892.    ,    3.    ,   34.5   ,    0.    ,    0.    ,    7.8292,
           0.    ,    1.    ,    0.    ],
       [ 893.    ,    3.    ,   47.    ,    1.    ,    0.    ,    7.    ,
           0.    ,    0.    ,    1.    ],
       [ 894.    ,    2.    ,   62.    ,    0.    ,    0.    ,    9.6875,
           0.    ,    1.    ,    0.    ]])

In [17]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators = 1000)
rf_model.fit(training_data, training_target)
print(rf_model)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)


In [18]:
expected = training_target
predicted = rf_model.predict(training_data)
print(metrics.accuracy_score(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))
print(metrics.roc_auc_score(expected, predicted))

0.982042648709
[[543   6]
 [ 10 332]]
0.979915636085


In [19]:
print(rf_model.feature_importances_)
print(training.columns)

[ 0.08357204  0.25132123  0.04983364  0.0460347   0.27784624  0.02200596
  0.01257706  0.25680913]
Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare',
       'C', 'Q', 'female'],
      dtype='object')


In [20]:
from sklearn import cross_validation
from sklearn.linear_model import LogisticRegression

num_folds = 10
num_instances = len(training_data)
kfold = cross_validation.KFold(n=num_instances, n_folds=num_folds)
model = LogisticRegression()
results = cross_validation.cross_val_score(model, training_data, training_target, cv=kfold)
print(results)
print(results.mean())
print(results.std())

C:\Users\Shail\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


[ 0.8         0.82022472  0.75280899  0.79775281  0.75280899  0.76404494
  0.75280899  0.75280899  0.86516854  0.79775281]
0.785617977528
0.0357748291993


In [21]:
predicted = rf_model.predict(test_data[:,1:])
submission = np.c_[test_data[:,0].astype(int), predicted.astype(int)]
submission = pd.DataFrame(submission, columns=['PassengerId', 'Survived'])
submission.to_csv('C:/Users/Shail/Desktop/Datasets/submission_rf.csv', index=False)
submission.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         1
4          896         0